/* สร้าง data/seed.sql จากไฟล์ข้อมูลของเว็บ — ฐานข้อมูลต้องสร้างใหม่จากวอลต์ได้เสมอ
   ห้ามแก้ข้อมูลในฐานข้อมูลโดยตรง ให้แก้ที่วอลต์แล้วรัน npm run build:db
   Run: npm run build:db                                                              */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import * as D from "../src/data.js";
import * as O from "../src/obeData.js";
import * as C from "../src/cloData.js";
import * as K from "../src/ksecData.js";
import * as CK from "../src/courseKsecData.js";
import * as P from "../src/ksecPedagogyData.js";
import * as T from "../src/teachingData.js";
import * as F from "../src/facultyData.js";
import * as R from "../src/refData.js";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const OUT = path.join(root, "data/seed.sql");

/* ── helper ── */
const q = v => v === null || v === undefined || v === "" ? "NULL" : `'${String(v).replace(/'/g, "''")}'`;
const n = v => v === null || v === undefined || Number.isNaN(v) ? "NULL" : String(v);
const b = v => v ? "true" : "false";
const out = [];
let rowCount = 0;
function insert(table, cols, rows) {
  if (!rows.length) return;
  rowCount += rows.length;
  out.push(`-- ${table} (${rows.length})`);
  out.push(`INSERT INTO ${table} (${cols.join(", ")}) VALUES`);
  out.push(rows.map(r => "  (" + r.join(", ") + ")").join(",\n") + ";");
  out.push("");
}

/* แยก "3(2-2-5)" เป็นตัวเลข */
function credit(text) {
  const m = String(text || "").match(/^(\d+)\s*\((\d+)-(\d+)-(\d+)\)/);
  if (m) return { cr: +m[1], lec: +m[2], lab: +m[3], self: +m[4] };
  const only = String(text || "").match(/^(\d+)/);
  return { cr: only ? +only[1] : 0, lec: null, lab: null, self: null };
}

const PROG = "AISE-2570";
const ELECTIVE_GROUP = "elec";

out.push("-- AUTO-GENERATED by scripts/build-db-seed.mjs — do not edit by hand.");
out.push("-- Regenerate with: npm run build:db");
out.push("BEGIN;");
out.push("");

/* ── 1. หลักสูตรและอาจารย์ ── */
insert("programme",
  ["id", "name_th", "name_en", "degree_th", "degree_abbr_th", "degree_en", "degree_abbr_en",
   "total_credits", "years", "faculty_office", "status"],
  [[q(PROG),
    q("หลักสูตรวิศวกรรมศาสตรบัณฑิต สาขาวิชาวิศวกรรมปัญญาประดิษฐ์และระบบอัจฉริยะ"),
    q("Bachelor of Engineering Program in Artificial Intelligence and Intelligent Systems Engineering"),
    q("วิศวกรรมศาสตรบัณฑิต (วิศวกรรมปัญญาประดิษฐ์และระบบอัจฉริยะ)"),
    q("วศ.บ. (วิศวกรรมปัญญาประดิษฐ์และระบบอัจฉริยะ)"),
    q("Bachelor of Engineering (Artificial Intelligence and Intelligent Systems Engineering)"),
    q("B.Eng. (Artificial Intelligence and Intelligent Systems Engineering)"),
    n(D.TOTAL_CREDITS), n(4),
    q("คณะวิศวกรรมศาสตร์และเทคโนโลยีอุตสาหกรรม มหาวิทยาลัยกาฬสินธุ์"),
    q("หลักสูตรใหม่ พ.ศ. 2570")]]);

insert("faculty_member",
  ["id", "programme_id", "order_no", "academic_rank", "rank_abbr", "full_name", "role",
   "expertise_field", "is_responsible", "qualification_match"],
  F.FACULTY.map(f => [n(f.id), q(PROG), n(f.id), q(f.rank), q(f.rankShort), q(f.name),
    q(f.role), q(f.field), b(true), q(f.qualified)]));

insert("faculty_degree",
  ["faculty_id", "level", "abbr", "major", "institution", "year_be"],
  F.FACULTY.flatMap(f => f.degrees.map(d =>
    [n(f.id), q(d.level), q(d.abbr), q(d.major), q(d.inst), n(d.year)])));

/* ── 2. โครงสร้างและรายวิชา ── */
insert("course_group",
  ["id", "no", "name_th", "code_prefix", "credits", "course_count", "is_elective_pool", "pick_count", "note"],
  D.STRUCTURE.map(s => {
    const pool = s.id === ELECTIVE_GROUP;
    return [q(s.id), q(s.no), q(s.name), q(s.code), n(s.credits), n(s.n),
      b(pool), pool ? n(C.ELECTIVE_PICK) : "NULL", q(s.note)];
  }));

insert("track", ["id", "name_th", "name_en"],
  [1, 2, 3].map(i => [q("T" + i), q(D.TRACK_NAME[i]), q("Track " + i)]));

const groupIds = new Set(D.STRUCTURE.map(s => s.id));
const courses = D.COURSES.filter(c => groupIds.has(c.g));
const skippedCourses = D.COURSES.filter(c => !groupIds.has(c.g));
if (skippedCourses.length) console.log(`  !! ข้ามรายวิชาที่กลุ่มไม่อยู่ใน STRUCTURE: ${skippedCourses.map(c => c.c + "(" + c.g + ")").join(", ")}`);

insert("course",
  ["code", "programme_id", "group_id", "short_name", "name_th", "name_en", "credit_text", "credits",
   "lecture_hours", "lab_hours", "self_hours", "study_year", "semester", "pending_semester",
   "description_th", "description_en"],
  courses.map(c => {
    const cr = credit(c.cr);
    return [q(c.c), q(PROG), q(c.g), q(c.s), q(c.t), q(c.e), q(c.cr), n(cr.cr),
      n(cr.lec), n(cr.lab), n(cr.self), n(c.y), n(c.sem), b(c.pendingSemester),
      q(c.d), q(c.dEn)];
  }));

const known = new Set(courses.map(c => c.c));
const prereqRows = [];
courses.forEach(c => {
  (c.h || []).forEach(p => known.has(p) && prereqRows.push([q(c.c), q(p), q("hard")]));
  (c.w || []).forEach(p => known.has(p) && prereqRows.push([q(c.c), q(p), q("weak")]));
  (c.co || []).forEach(p => known.has(p) && prereqRows.push([q(c.c), q(p), q("coreq")]));
});
insert("course_prereq", ["course_code", "prereq_code", "kind"], prereqRows);

insert("study_plan", ["id", "name_th", "note"],
  Object.values(D.PLANS).map(p => [q(p.key), q(p.name), q(p.sub)]));

insert("study_plan_course", ["plan_id", "course_code", "semester"],
  Object.values(D.PLANS).flatMap(p =>
    D.coursesOfPlan(p.key)
      .filter(c => known.has(c.c) && c.sem >= 1 && c.sem <= 8)
      .map(c => [q(p.key), q(c.c), n(c.sem)])));

/* ── 3. ผลลัพธ์การเรียนรู้ ── */
insert("plo", ["id", "name_th", "title_full", "abet_so", "bloom_domain"],
  [1, 2, 3, 4, 5, 6, 7].map(i => {
    const d = D.PLO_DETAIL[i] || {};
    return [n(i), q(D.PLO_NAME[i]), q(d.title), q(d.so), q(d.type)];
  }));

insert("ylo", ["id", "title_th", "title_en", "level_note", "statement"],
  [1, 2, 3, 4].map(i => {
    const y = D.YLO_DETAIL[i];
    return [n(i), q(y.title), q(y.en), q(y.level), q(y.text)];
  }));

insert("sub_ylo", ["id", "ylo_id", "statement"],
  [1, 2, 3, 4].flatMap(i => (D.YLO_DETAIL[i].sub || []).map(s => [q(s[0]), n(i), q(s[1])])));

/* ── 4. ทักษะ ชุดทักษะ KSA ── */
insert("skill_group", ["id", "name_th", "color"],
  Object.entries(O.GROUPS).map(([id, g]) => [q(id), q(g.name), q(g.color)]));

insert("skill_set", ["id", "group_id", "name_th", "name_en", "kind"],
  O.SKILL_SETS.map(s => [q(s.id), q(s.g), q(s.name), q(s.en), q(s.type)]));

const allSkills = [...O.HARD_SKILLS, ...O.SOFT_SKILLS, ...O.ENGINEERING_FOUNDATIONS];
insert("skill",
  ["id", "family", "rank_no", "name_en", "is_core", "scope", "market_evidence", "benchmark"],
  allSkills.map(s => [q(s.id), q(s.id.replace(/\d+$/, "")), n(s.rank), q(s.name),
    b(s.core), q(s.scope), q(s.market), q(s.bench)]));

/* ทักษะอยู่ได้หลายชุด — รวมทั้งที่ประกาศใน SKILL_SETS.skills และฟิลด์ set ของตัวทักษะเอง */
const skillIds = new Set(allSkills.map(s => s.id));
const setSkill = new Set();
O.SKILL_SETS.forEach(ss => (ss.skills || []).forEach(k => skillIds.has(k) && setSkill.add(ss.id + "|" + k)));
allSkills.forEach(s => s.set && setSkill.add(s.set + "|" + s.id));
insert("skill_set_skill", ["skill_set_id", "skill_id"],
  [...setSkill].map(x => x.split("|")).map(([a, b_]) => [q(a), q(b_)]));

insert("skill_track", ["skill_id", "track_id", "role"],
  allSkills.flatMap(s => Object.entries(s.track || {})
    .filter(([, mark]) => mark === "●" || mark === "○")
    .map(([t, mark]) => [q(s.id), q(t), q(mark === "●" ? "core" : "support")])));

const ksecAll = [
  ...K.KNOWLEDGE.map(r => ({ ...r, dim: "K" })),
  ...K.SKILLS_KSEC.map(r => ({ ...r, dim: "S" })),
  ...K.ETHICS.map(r => ({ ...r, dim: "E" })),
  ...K.CHARACTER.map(r => ({ ...r, dim: "C" }))
];
insert("ksa_item",
  ["id", "dimension", "seq", "name_th", "scope", "covers", "evidence", "target_depth", "skill_kind"],
  ksecAll.map(r => [q(r.id), q(r.dim), n(+r.id.slice(1)), q(r.name), q(r.scope), q(r.covers),
    q(r.evidence), q((r.level || "").match(/B[1-6]/)?.[0]), q(r.type)]));

insert("ksa_can_do", ["ksa_id", "seq", "statement"],
  ksecAll.flatMap(r => (r.can || []).map((c, i) => [q(r.id), n(i + 1), q(c)])));

insert("ksa_skill", ["ksa_id", "skill_id"],
  ksecAll.flatMap(r => [...new Set((r.skills || []))].map(s => [q(r.id), q(s)])));

insert("ksa_plo", ["ksa_id", "plo_id"],
  ksecAll.flatMap(r => [...new Set((r.plo || []))].map(p => [q(r.id), n(p)])));

/* CLO — ใช้เลขลำดับที่กำหนดเองเพื่อให้ตารางเชื่อมอ้างได้ */
const cloId = new Map();
let seq = 0;
const cloRows = [], cloPlo = [], cloYlo = [], cloSet = [], cloKsec = [];

/* รหัสวิชาบางตัวถูกใช้กับสองรายวิชาที่ต่างกัน (ข้อบกพร่องในข้อมูลต้นทาง)
   ฐานข้อมูลบังคับ UNIQUE(course_code, no) จึงต้องเก็บรายการแรกและเตือนไว้ */
const dupCodes = Object.entries(
  C.CLO_LIST.reduce((m, e) => ((m[e.c] = (m[e.c] || 0) + 1), m), {})
).filter(([, k]) => k > 1).map(([c]) => c);
if (dupCodes.length) {
  console.log(`  !! รหัสวิชาซ้ำในข้อมูลต้นทาง ${dupCodes.length} ตัว — เก็บรายการแรกเท่านั้น: ${dupCodes.join(", ")}`);
}
const seenCourse = new Set();

C.CLO_LIST.filter(e => known.has(e.c)).forEach(e => {
  if (seenCourse.has(e.c)) return;
  seenCourse.add(e.c);
  e.clos.forEach(clo => {
    const id = ++seq;
    cloId.set(e.c + "#" + clo.n, id);
    cloRows.push([n(id), q(e.c), n(clo.n), q(clo.t), q(clo.evidence), q(clo.primarySet)]);
    (clo.plo || []).forEach(([p, lv]) => cloPlo.push([n(id), n(p), q(lv)]));
    (clo.ylo || []).forEach(y => cloYlo.push([n(id), q(y)]));
    [...new Set(clo.sets || [])].forEach(s =>
      cloSet.push([n(id), q(s), b(s === clo.primarySet)]));
    const k = CK.cloKsec(e.c, clo.n);
    if (k) [...k.K, ...k.S, ...k.E, ...k.C].forEach(code => cloKsec.push([n(id), q(code), q("stated")]));
  });
});
insert("clo", ["id", "course_code", "no", "statement", "evidence", "primary_skill_set"], cloRows);
insert("clo_plo", ["clo_id", "plo_id", "level"], cloPlo);
insert("clo_sub_ylo", ["clo_id", "sub_ylo_id"], cloYlo);
insert("clo_skill_set", ["clo_id", "skill_set_id", "is_primary"], cloSet);

insert("course_plo", ["course_code", "plo_id", "role"],
  courses.flatMap(c => (c.p || []).map(p => [q(c.c), n(p), q("host")])));

insert("clo_ksa", ["clo_id", "ksa_id", "source"], cloKsec);

insert("course_ksa", ["course_code", "ksa_id", "source"],
  Object.values(CK.COURSE_KSEC).filter(c => known.has(c.code)).flatMap(c =>
    [...c.K, ...c.S, ...c.E, ...c.C].map(k => [q(c.code), q(k), q(c.derivedFrom ? "derived" : "stated")])));

insert("course_skill_set", ["course_code", "skill_set_id"],
  Object.values(CK.COURSE_KSEC).filter(c => known.has(c.code))
    .flatMap(c => [...new Set((c.aisk || []))].map(a => [q(c.code), q(a)])));

/* ── 5. ที่มาของหลักสูตร ── */
insert("stakeholder", ["id", "name_th", "sample_size", "priority", "expectation"],
  O.STAKEHOLDERS.map(s => [q(s.id), q(s.name), n(s.sample), q(s.prio), q(s.expect)]));

insert("need", ["id", "source_kind", "statement", "evidence"],
  O.NEEDS.map(x => [q(x.id), q(x.src), q(x.text), q(x.evidence)]));

const needIds = new Set(O.NEEDS.map(x => x.id));
insert("stakeholder_need", ["stakeholder_id", "need_id"],
  O.STAKEHOLDERS.flatMap(s => [...new Set((s.needs || []).filter(x => needIds.has(x)))].map(x => [q(s.id), q(x)])));

insert("need_skill_set", ["need_id", "skill_set_id"],
  O.NEEDS.flatMap(x => [...new Set((x.sets || []))].map(s => [q(x.id), q(s)])));

insert("graduate_attribute", ["id", "name_th", "washington_accord", "abet_so"],
  O.GA.map(g => [q(g.id), q(g.name), q(g.wa), q(g.abet)]));

insert("ga_plo", ["ga_id", "plo_id"],
  O.GA.flatMap(g => [...new Set((g.plo || []))].map(p => [q(g.id), n(p)])));

/* ── 6. อาชีพ ── */
insert("career", ["id", "track_id", "status", "name_th", "name_en", "rationale"],
  D.CAREERS.map(c => [q(c.id), c.track ? q("T" + c.track) : "NULL", q(c.st), q(c.th), q(c.en), q(c.why)]));

insert("career_course", ["career_id", "course_code"],
  D.CAREERS.flatMap(c =>
    [...new Set((c.courses || []).filter(x => known.has(x)))].map(x => [q(c.id), q(x)])));

/* ── 6b. ประกาศงานจริงจาก JobsDB — src/jobsData.json ── */
const JOBS_FILE = path.join(root, "src/jobsData.json");
if (fs.existsSync(JOBS_FILE)) {
  const jd = JSON.parse(fs.readFileSync(JOBS_FILE, "utf8"));
  const jobs = jd.jobs || [];
  const careerIds = new Set(D.CAREERS.map(c => c.id));

  /* กลุ่มย่อยอาชีพ — รวบจากทั้ง searchMatches และ classifiedMatches ของทุกประกาศ */
  const sub = new Map();
  jobs.forEach(j => [...(j.searchMatches || []), ...(j.classifiedMatches || [])]
    .forEach(m => {
      if (m.subId && careerIds.has(m.careerId) && !sub.has(m.subId)) {
        sub.set(m.subId, { id: m.subId, career: m.careerId, name: m.subName || null });
      }
    }));
  insert("career_subgroup", ["id", "career_id", "name_th"],
    [...sub.values()].map(s => [q(s.id), q(s.career), q(s.name)]));

  insert("job_posting", ["id", "external_id", "source", "title", "company", "posted_on"],
    jobs.map((j, i) => [n(i + 1), q(j.id), q(jd.meta?.source || "JobsDB"),
      q(j.title), q(j.company), q((j.listingDate || "").slice(0, 10) || null)]));

  /* ใช้เฉพาะ classifiedMatches ที่ผ่านการจำแนกแล้ว ไม่ใช่ searchMatches ที่เป็นผลค้นหาดิบ */
  const jcm = [];
  jobs.forEach((j, i) => {
    const seen = new Set();
    (j.classifiedMatches || []).forEach(m => {
      if (!careerIds.has(m.careerId) || seen.has(m.careerId)) return;
      seen.add(m.careerId);
      jcm.push([n(i + 1), q(m.careerId), sub.has(m.subId) ? q(m.subId) : "NULL",
        q(m.role), m.confidence == null ? "NULL" : n(m.confidence)]);
    });
  });
  insert("job_career_match", ["job_id", "career_id", "subgroup_id", "match_role", "confidence"], jcm);

  const js = [];
  jobs.forEach((j, i) => {
    const seen = new Set();
    (j.skills || []).forEach(s => {
      if (!s.name || seen.has(s.name)) return;
      seen.add(s.name);
      js.push([n(i + 1), q(s.name), q(s.category)]);
    });
  });
  insert("job_skill", ["job_id", "skill_label", "category"], js);
} else {
  console.log("  !! ไม่พบ src/jobsData.json — ข้ามตารางกลุ่มประกาศงาน");
}

/* ── 7. การสอนและการประเมิน ── */
insert("teaching_strategy", ["id", "name_th", "name_en", "how", "tools"],
  T.STRATEGIES.map((s, i) => {
    const m = s.name.match(/^(\d+)\.\s*(.*)$/);
    const rest = m ? m[2] : s.name;
    const en = rest.match(/\(([^)]+)\)\s*$/);
    return [n(m ? +m[1] : i + 1),
      q(rest.replace(/·?\s*\([^)]+\)\s*$/, "").replace(/·\s*$/, "").trim()),
      q(en ? en[1] : null), q(s.how), q(s.tools)];
  }));

insert("strategy_plo", ["strategy_id", "plo_id", "level_from", "level_to"],
  T.STRATEGIES.flatMap((s, i) => {
    const m = s.name.match(/^(\d+)\./);
    const sid = m ? +m[1] : i + 1;
    return (s.plos || []).map(p => {
      const lv = (s.levelOf || {})[p] || "";
      const parts = lv.split(/[–-]/).map(x => x.trim()).filter(x => /^[IRM]$/.test(x));
      return [n(sid), n(p), q(parts[0] || null), q(parts[1] || parts[0] || null)];
    });
  }));

insert("plo_assessment", ["plo_id", "method", "evidence", "mastery_point", "assessor"],
  Object.entries(T.ASSESSMENT).map(([p, a]) => [n(+p), q(a.method), q(a.evidence), q(a.mastery), q(a.assessor)]));

insert("ksa_pedagogy",
  ["ksa_id", "teaching_strategy", "how", "assessment_method", "artifact", "is_tailored", "source"],
  P.KSEC_PEDAGOGY.map(r => [q(r.id), q(r.teach), q(r.how), q(r.assess), q(r.artifact),
    b(r.tailored), q("authored")]));

insert("ksa_anchor_course", ["ksa_id", "course_code", "rank_no", "source"],
  P.KSEC_PEDAGOGY.flatMap(r => r.anchors
    .filter(a => known.has(a.c))
    .map((a, i) => [q(r.id), q(a.c), n(i + 1), q("derived")])));

/* ── 8. เอกสารอ้างอิง ── */
insert("reference_doc", ["category", "name", "organisation", "url", "used_for"],
  (R.STANDARDS || []).map(s => [q("มาตรฐานและกรอบสากล"), q(s.name), q(s.org), q(s.url), q(s.use)])
    .concat((R.BIB || []).flatMap(g => (g.items || []).map(it =>
      [q(g.g), q(it.text), "NULL", q(it.url), "NULL"]))));

out.push("COMMIT;");
fs.writeFileSync(OUT, out.join("\n"), "utf8");
console.log(`seed.sql: ${rowCount} แถว · ${courses.length} รายวิชา · ${cloRows.length} CLO · ${ksecAll.length} KSA`);
